server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

spring:
  cloud:
    gateway:
      routes:
        - id: auth-route
          uri: lb://AuthService
          predicates:
            - Path=/auth/**


             - id: zone-route
          uri: lb://Zone-Service
          predicates:
            - Path=/api/zones/**
          filters:
            - AuthenticationFilter

jwt:
  secret: "199205051b6f7353e4a9c33b129f3d0e86559d53ba6b0276ef937da080da7307"
